### ISSUE TITLE
Issue with importing fixed Genbank file into database 

### ISSUE THREAD

**Issue by rayesd** [scresawn/phamerator#23]
When I try to import the fixed Genbank file CharlieAJ I get this issue. Not sure how "phageID" works so I don't know where to start in terms of fixing this problem.
![screen shot 2016-10-25 at 12 32 55 pm](https://cloud.githubusercontent.com/assets/23020008/19695059/b679c974-9aaf-11e6-9e4c-44b6daed7ec0.png)

**Comment by scresawn** [comment]
I'm marking this issue as closed because this repository is for the Phamerator web and mobile applications, while your error looks to be on the server side. If you are a member of SEA-PHAGES and are looking for software support, please use the forums there. Also, you may find using James Lamine's [PhamDB](https://github.com/jglamine/phamdb) an easier way to construct new Phamerator databases than using the python scripts directly.
